### ISSUE TITLE
Add gradle support

### ISSUE THREAD

**Issue by josomers** [josomers/android-slidingup-panel#2]
Add Android Gradle support to the project for Android Studio.

**Comment by Gerst20051** [comment]
Why not just use [https://github.com/umano/AndroidSlidingUpPanel](https://github.com/umano/AndroidSlidingUpPanel)? Just to clarify my question... After over 3 years did the umano library never get updated to support the additional features you added? If not, I would love for your version of this library to support gradle.

**Comment by josomers** [comment]
Hi @Gerst20051, I've not updated the project anymore. Seems like the original library got updated in the meanwhile, but I'm not sure if all the fixes I did are included. :-)
